
-- Admin user ID (assuming Jericho is admin with user_id = 1)
SET @admin_user_id = 1;

-- Sample user ID (Customer, e.g., user_id = 5)
SET @customer_user_id = 5;

-- BOOK PROCEDURES (DONE) --
CALL getAllBooks();
CALL getBookDetails(1); -- Assuming book_id = 1
CALL updateBookPrice(1, 350.00); -- updates the specific book price of a book --
CALL updateStockQuantity(1, 30);
CALL removeBooks(6); -- Delete book with book_id = 6

-- USER PROCEDURES (DONE) --
CALL getAllUsers();
CALL addUsers('Test User', 'testuser@email.com', 'testpass');
CALL removeUsers(6); -- Remove user with user_id = 6 (if exists)

-- CART PROCEDURES
CALL addToCart(1, 1, 2); -- Add 2 qty of book_id = 1
CALL getCart(1);
CALL removeFromCart(1, 1);
CALL clearCart(1);

-- ORDER & TRANSACTION PROCEDURES (transactions in the app first and use TestUser AND THEN run these) -- 
CALL getOrders(7); -- change this to the ID of testUser on your side --
CALL getUserOrderHistory(7);

-- ADMIN PROCEDURES 
CALL getAllOrders(1); 
CALL getAllTransactionLogs(1);
CALL updateUserRole(5, 5, 'Staff'); 
CALL updateBookDetails(1, 2, 'Updated Title', 'Updated Genre', 199.99, 15);
CALL updateExchangeRate(1, 'USD', 56.5000);

-- If you want to view the logs generated by triggers:
SHOW TRIGGERS;
SELECT * FROM price_audit;
SELECT * FROM stock_log;
SELECT * FROM user_registration_log;
SELECT * FROM cart_deletion_log;
SELECT * FROM role_change_log;
SELECT * FROM book_deletion_log;
SELECT * FROM admin_action_log;
